services:
  - type: web
    name: quickbite-angular-restaurant-app
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:production
    healthCheckPath: /api/health
    autoDeployTrigger: commit
